name: CI/CD Workflow

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}
  AWS_DEFAULT_REGION: 'eu-west-2'
  ECS_CLUSTER: 'wordpress-terraform-dev'
  ECS_SERVICE: 'wordpress-terraform-dev'

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
  pull_request:
    types:
      - closed

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo tag and exit
        run: |
          VERSION=${{ github.ref_name }}
          echo "${{ github.ref_name }}" | cut -c2-"
          exit 1

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd ./wordpress/wp-content/themes/juicystrap
          rm -rf node_modules
          npm install

  build-assets:
    runs-on: ubuntu-latest
    needs: npm
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd ./wordpress/wp-content/themes/juicystrap
          npm install

      - name: Build assets
        run: |
          cd ./wordpress/wp-content/themes/juicystrap
          npm run production

  prettier:
    runs-on: ubuntu-latest
    needs: npm
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd ./wordpress/wp-content/themes/juicystrap
          npm install

      - name: Run Prettier
        run: |
          cd ./wordpress/wp-content/themes/juicystrap
          npm run lint:prettier
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed')

  eslint:
    runs-on: ubuntu-latest
    needs: npm
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd ./wordpress/wp-content/themes/juicystrap
          npm install

      - name: Run ESLint
        run: |
          cd ./wordpress/wp-content/themes/juicystrap
          npm run lint:js
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed')

  stylelint:
    runs-on: ubuntu-latest
    needs: npm
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd ./wordpress/wp-content/themes/juicystrap
          npm install

      - name: Run StyleLint
        run: |
          cd ./wordpress/wp-content/themes/juicystrap
          npm run lint:style
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed')

  build-docker:
    runs-on: ubuntu-latest
    needs: [build-assets, prettier, eslint, stylelint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with: 
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        run: |
          docker build -t "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" . --platform linux/amd64
          if
          [ ${{ github.ref_name }} =~ /^v(\S)+-production/ ]; then docker tag "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}" "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"; 
          fi
          docker push "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Deploy to AWS ECS
        run: |
          aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --force-new-deployment --no-cli-pager
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event_name != 'delete')